services:
  web:
    container_name: portfolio-dev
    build:
      context: .
      dockerfile_inline: |
        FROM node:20-alpine
        WORKDIR /app
        RUN apk add --no-cache libc6-compat
        COPY package*.json ./
        RUN npm install
        COPY . .
        CMD ["npm", "run", "dev"]
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    restart: always